// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCndDr8ugdWPG-gNDlyIPPSLBxRGFblDTE',
    appId: '1:951909592865:web:a9858ac7bdb178af095860',
    messagingSenderId: '951909592865',
    projectId: 'devfest-workshop-flutter-2022',
    authDomain: 'devfest-workshop-flutter-2022.firebaseapp.com',
    storageBucket: 'devfest-workshop-flutter-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV6e_ectOvFKJF5lAHvq1o09_tgM11Q3g',
    appId: '1:951909592865:android:50cd2f342c26da84095860',
    messagingSenderId: '951909592865',
    projectId: 'devfest-workshop-flutter-2022',
    storageBucket: 'devfest-workshop-flutter-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsljbtSOsG_0mfvxi8ZPTY0MkC73Nb7wM',
    appId: '1:951909592865:ios:a5fd1a29adbdd94b095860',
    messagingSenderId: '951909592865',
    projectId: 'devfest-workshop-flutter-2022',
    storageBucket: 'devfest-workshop-flutter-2022.appspot.com',
    iosClientId: '951909592865-dp1jq6lms88nj08vk68blcbf9khqdn6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.workshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsljbtSOsG_0mfvxi8ZPTY0MkC73Nb7wM',
    appId: '1:951909592865:ios:a5fd1a29adbdd94b095860',
    messagingSenderId: '951909592865',
    projectId: 'devfest-workshop-flutter-2022',
    storageBucket: 'devfest-workshop-flutter-2022.appspot.com',
    iosClientId: '951909592865-dp1jq6lms88nj08vk68blcbf9khqdn6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.workshop',
  );
}
